//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infoOnTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Врач
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Врач()
        {
            this.Пациент = new HashSet<Пациент>();
        }
    
        public int Id_doc { get; set; }
        public int id_cab { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public bool Готовность { get; set; }
        public string Должность { get; set; }
        public string Квалификация { get; set; }
        public byte[] Фото { get; set; }
    
        public virtual Кабинет Кабинет { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пациент> Пациент { get; set; }
    }
}
